-- Drop the existing table if it exists (re-create for precision)
DROP TABLE IF EXISTS public.digital_twin_simulation_logs;

-- Create a robust table to store Digital Twin simulation steps
CREATE TABLE public.digital_twin_simulation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Core Context
    campus_id TEXT NOT NULL,
    simulation_date DATE NOT NULL,
    simulation_time TEXT NOT NULL, -- Storing as text (e.g. "19:00") for easier frontend matching
    
    -- Energy Generation Data (The values shown in your visualizer)
    solar_generated NUMERIC DEFAULT 0,
    wind_generated NUMERIC DEFAULT 0,
    
    -- Battery State
    battery_output NUMERIC DEFAULT 0, -- "BAT.OUT" in your image
    battery_percentage NUMERIC DEFAULT 0, -- Crucial for state persistence
    
    -- Consumption & Savings
    grid_used NUMERIC DEFAULT 0,      -- Explicitly tracking grid dependency
    total_load NUMERIC DEFAULT 0,     -- The total load context
    cost_saved NUMERIC DEFAULT 0,     -- "SAVED" in your image
    
    -- Audit
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraints
    CONSTRAINT unique_simulation_step UNIQUE (campus_id, simulation_date, simulation_time)
);

-- Enable Row Level Security (RLS) - Optional/Recommended
ALTER TABLE public.digital_twin_simulation_logs ENABLE ROW LEVEL SECURITY;

-- Policy to allow anonymous/service_role access (adjust based on your auth needs)
CREATE POLICY "Enable all access for service role" ON public.digital_twin_simulation_logs
    FOR ALL USING (true) WITH CHECK (true);
